# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class ChatServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_stream(
        '/grpc.ChatServer/SendMessage',
        request_serializer=messenger__pb2.Msg.SerializeToString,
        response_deserializer=messenger__pb2.WarningMsg.FromString,
        )
    self.ChatStream = channel.unary_stream(
        '/grpc.ChatServer/ChatStream',
        request_serializer=messenger__pb2.User.SerializeToString,
        response_deserializer=messenger__pb2.Msg.FromString,
        )
    self.UsersOnline = channel.unary_stream(
        '/grpc.ChatServer/UsersOnline',
        request_serializer=messenger__pb2.Empty.SerializeToString,
        response_deserializer=messenger__pb2.Usr.FromString,
        )
    self.CreateConnection = channel.unary_unary(
        '/grpc.ChatServer/CreateConnection',
        request_serializer=messenger__pb2.User.SerializeToString,
        response_deserializer=messenger__pb2.Connection.FromString,
        )
    self.CheckMessageList = channel.unary_unary(
        '/grpc.ChatServer/CheckMessageList',
        request_serializer=messenger__pb2.Usr.SerializeToString,
        response_deserializer=messenger__pb2.Usr.FromString,
        )


class ChatServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChatStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UsersOnline(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateConnection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckMessageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_stream_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=messenger__pb2.Msg.FromString,
          response_serializer=messenger__pb2.WarningMsg.SerializeToString,
      ),
      'ChatStream': grpc.unary_stream_rpc_method_handler(
          servicer.ChatStream,
          request_deserializer=messenger__pb2.User.FromString,
          response_serializer=messenger__pb2.Msg.SerializeToString,
      ),
      'UsersOnline': grpc.unary_stream_rpc_method_handler(
          servicer.UsersOnline,
          request_deserializer=messenger__pb2.Empty.FromString,
          response_serializer=messenger__pb2.Usr.SerializeToString,
      ),
      'CreateConnection': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConnection,
          request_deserializer=messenger__pb2.User.FromString,
          response_serializer=messenger__pb2.Connection.SerializeToString,
      ),
      'CheckMessageList': grpc.unary_unary_rpc_method_handler(
          servicer.CheckMessageList,
          request_deserializer=messenger__pb2.Usr.FromString,
          response_serializer=messenger__pb2.Usr.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
