# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmessenger.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\'\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tothername\x18\x02 \x01(\t\"\x13\n\x03Usr\x12\x0c\n\x04name\x18\x01 \x01(\t\"V\n\x03Msg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tothername\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\x0c\x12\x12\n\nciphertext\x18\x04 \x01(\x0c\x12\x0b\n\x03tag\x18\x05 \x01(\x0c\" \n\nConnection\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\"\x1d\n\nWarningMsg\x12\x0f\n\x07warning\x18\x01 \x01(\t2\xe6\x01\n\nChatServer\x12,\n\x0bSendMessage\x12\t.grpc.Msg\x1a\x10.grpc.WarningMsg0\x01\x12%\n\nChatStream\x12\n.grpc.User\x1a\t.grpc.Msg0\x01\x12\'\n\x0bUsersOnline\x12\x0b.grpc.Empty\x1a\t.grpc.Usr0\x01\x12\x30\n\x10\x43reateConnection\x12\n.grpc.User\x1a\x10.grpc.Connection\x12(\n\x10\x43heckMessageList\x12\t.grpc.Usr\x1a\t.grpc.Usrb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=32,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='grpc.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='othername', full_name='grpc.User.othername', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=73,
)


_USR = _descriptor.Descriptor(
  name='Usr',
  full_name='grpc.Usr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.Usr.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=94,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='grpc.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.Msg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='othername', full_name='grpc.Msg.othername', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='grpc.Msg.nonce', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='grpc.Msg.ciphertext', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='grpc.Msg.tag', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=182,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='grpc.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='successful', full_name='grpc.Connection.successful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=216,
)


_WARNINGMSG = _descriptor.Descriptor(
  name='WarningMsg',
  full_name='grpc.WarningMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warning', full_name='grpc.WarningMsg.warning', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=247,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Usr'] = _USR
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['WarningMsg'] = _WARNINGMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.User)
  ))
_sym_db.RegisterMessage(User)

Usr = _reflection.GeneratedProtocolMessageType('Usr', (_message.Message,), dict(
  DESCRIPTOR = _USR,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Usr)
  ))
_sym_db.RegisterMessage(Usr)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Msg)
  ))
_sym_db.RegisterMessage(Msg)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTION,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Connection)
  ))
_sym_db.RegisterMessage(Connection)

WarningMsg = _reflection.GeneratedProtocolMessageType('WarningMsg', (_message.Message,), dict(
  DESCRIPTOR = _WARNINGMSG,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.WarningMsg)
  ))
_sym_db.RegisterMessage(WarningMsg)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='grpc.ChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=250,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='grpc.ChatServer.SendMessage',
    index=0,
    containing_service=None,
    input_type=_MSG,
    output_type=_WARNINGMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='grpc.ChatServer.ChatStream',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_MSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UsersOnline',
    full_name='grpc.ChatServer.UsersOnline',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_USR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateConnection',
    full_name='grpc.ChatServer.CreateConnection',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_CONNECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckMessageList',
    full_name='grpc.ChatServer.CheckMessageList',
    index=4,
    containing_service=None,
    input_type=_USR,
    output_type=_USR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
